// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireinject

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"layout/internal/handler/http"
	app2 "layout/internal/handler/http/app"
	"layout/internal/handler/http/h5"
	"layout/internal/repository"
	"layout/internal/router"
	"layout/internal/service"
	"layout/pkg/db"
)

import (
	_ "layout/pkg/pprof"
)

// Injectors from wire.go:

func NewApp() (*gin.Engine, func(), error) {
	handlerHandler := http.NewHandler()
	gormDB := db.NewDB()
	serviceService := service.NewService(gormDB)
	repositoryRepository := repository.NewRepository(gormDB)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := app2.NewUserHandler(handlerHandler, userService)
	appRouter := &app2.Router{
		AppUser: userHandler,
	}
	h5Router := &h5.Router{}
	engine := router.NewServerHTTP(appRouter, h5Router)
	return engine, func() {
	}, nil
}

// wire.go:

var HandlerSet = wire.NewSet(http.ProviderSet, app2.ProviderSet, app2.StructProvider, h5.ProviderSet, h5.StructProvider)
