// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireinject

import (
	"github.com/google/wire"
	"layout/internal/handler/timer"
)

import (
	_ "layout/pkg/pprof"
)

// Injectors from wire.go:

func NewApp() (*timer.Job, func(), error) {
	jobJob := timer.NewJob()
	return jobJob, func() {
	}, nil
}

// wire.go:

var JobSet = wire.NewSet(timer.NewJob)
