basePath: /
definitions:
  service.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  service.UpdateProfileRequest:
    properties:
      avatar:
        type: string
      email:
        type: string
      nickname:
        type: string
    required:
    - email
    type: object
info:
  contact: {}
  description: This is a YoYo Server pets
  title: YoYo API
  version: 0.0.1
paths:
  /api/user/info:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      summary: 用户登录注册
      tags:
      - 前台用户信息
  /api/user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录注册参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/service.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      summary: 用户登录注册
      tags:
      - 前台用户信息
  /api/user/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录注册参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/service.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      summary: 用户登录注册
      tags:
      - 前台用户信息
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
